### ISSUE TITLE
New NPM release?

### ISSUE THREAD

**Issue by DanGe42** [serverless-community-labs/serverless-plugin-simulate#100]
# This is a Bug Report (sort of)

I couldn't find a similar issue filed, but let me know if I missed anything.

### What went wrong?
Running `serverless simulate invoke -f hello` on the Serverless quick start setup (the hello world thing) results in the error

```
Serverless: Run function undefined...

  Error --------------------------------------------------

  Function undefined does not exist
```

### What did you expect should have happened?
It should have run the function.

### What was the config you used?
Not really relevant, but I'll provide it anyway:

```
service: sample-serverless
provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-plugin-simulate
```

### What stacktrace or error message from your provider did you see?
See answer to "What went wrong"

## Additional Data

The latest commit 9579e5dabb5b8b0fb2fcdcbe747325057ec43e5e resolved this issue 2 months ago. However, the last NPM package release was about a year ago. I'm currently working around this issue with by depending on this repo directly (e.g. `yarn add https://github.com/serverless-community-labs/serverless-plugin-simulate`), but I'd prefer to avoid this.
