### ISSUE TITLE
Querystring parameters break request path matching

### ISSUE THREAD

**Issue by jeffora** [serverless-community-labs/serverless-plugin-simulate#61]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

  `serverless-plugin-simulate` does not allow requests to defined paths through if they have querystrings:
  ```
  # console
  $ curl http://localhost:5000/version/check
  { ... json response from handler }
  $ curl http://localhost:5000/version/check?x=1
  { "message": "Forbidden" }
  
  # sls simulate apigateway -p 5000 (for ?x=1 error)
  Serverless: HTTP Event Not Found: Try checking your serverless.yml
  GET /version/check?x=1 403 0.504 ms - 23
  HTTP Event Not Found: Try checking your serverless.yml
  ```

* What did you expect should have happened?

  `curl http://localhost:5000/version/check` and `curl http://localhost:5000/version/check?x=1` should both execute handler and return response body

* What was the config you used?

  ```yml
  service: my-service
  plugins:
    - serverless-plugin-simulate
  provider:
    name: aws
    runtime: nodejs6.10
  functions:
    checkVersion:
      handler: lib/version.check
      events:
        - http:
            method: get
            path: version/check
            cors: true
  ```

* What stacktrace or error message from your provider did you see?

  ```
  Serverless: HTTP Event Not Found: Try checking your serverless.yml
  GET /version/check?x=1 403 0.504 ms - 23
  HTTP Event Not Found: Try checking your serverless.yml
  ```
